server:
  port: 8086
  servlet:
    context-path: /api

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #数据库类型
    database: MYSQL
    #控制台是否打印 SQL 语句
    show-sql: true

#系统参数配置
system:
  appKey: 1001215
  appSecret: 8888666
  address: http://192.168.2.123

